"""Generate the public example from explicit synthetic assumptions."""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent / "input"


def write_csv(name, rows):
    with (ROOT / name).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=rows[0])
        writer.writeheader()
        writer.writerows(rows)


def main():
    ROOT.mkdir(exist_ok=True)
    settings = {
        "data_origin": "Synthetic inputs generated by generate_inputs.py",
        "gpus_per_rack": 8, "rack_mass_kg": 600, "gpu_to_it_factor": 1.3,
        "quarter_hours": 2160, "training_runs_per_year": 2,
        "tokens_per_user_day": 2000, "training_efficiency": 0.5,
        "inference_efficiency": 0.2, "idle_power_fraction": 0.2,
        "max_power_fraction": 0.9, "cumulative_start": "Q09",
        "recovery_yield": 0.85,
        "growth": {
            "low": {"architecture_factor": 0.8, "user_factor": 0.7, "training_frequency_factor": 0.8},
            "central": {"architecture_factor": 1, "user_factor": 1, "training_frequency_factor": 1},
            "high": {"architecture_factor": 1.2, "user_factor": 1.4, "training_frequency_factor": 1.2}
        },
        "phases": {
            "single": {"litres_per_kw": 3, "density_kg_per_litre": 0.8,
                       "pue": 1.2, "annual_loss_fraction": 0.04, "evaporation_share": 0.0},
            "two": {"litres_per_kw": 2, "density_kg_per_litre": 1.2,
                    "pue": 1.1, "annual_loss_fraction": 0.08, "evaporation_share": 0.5}
        },
        "analysis": {
            "runs": 40, "seed": 17, "growth": "central", "cooling": "central",
            "strategy": "baseline", "background": "transition",
            "relative_ranges": {"demand": 0.15, "hardware": 0.1,
                                "coolant_intensity": 0.1, "pue_overhead": 0.1,
                                "impact_factors": 0.15},
            "sensitivity_fraction": 0.1
        }
    }
    scenarios = {
        "baseline": {}, "improved_pue": {"pue_overhead_factor": 0.75},
        "advanced_coolant": {"coolant_intensity_factor": 0.65},
        "coolant_recovery": {"recovery_rate": 0.7},
        "combined_strategy": {"pue_overhead_factor": 0.75,
                              "coolant_intensity_factor": 0.65, "recovery_rate": 0.7}
    }
    for name, data in (("settings", settings), ("scenarios", scenarios)):
        (ROOT / f"illustrative_{name}.json").write_text(json.dumps(data, indent=2) + "\n")
    rows = []
    for q in range(24):
        t = q / 23
        rows.append({
            "period": f"Q{q + 1:02}", "parameters_billion": round(5 * 1.08 ** q, 6),
            "training_flop_per_run": 2e23 * 1.12 ** q,
            "architectures": 2 + q // 8, "users_million": round(2 * 1.1 ** q, 6),
            "gpu_pflops": round(1 + 1.5 * t, 6), "gpu_board_kw": round(0.5 + 0.3 * t, 6),
            "training_utilization": round(0.6 + 0.1 * t, 6),
            "inference_utilization": round(0.3 + 0.1 * t, 6),
            "liquid_share_low": round(0.1 + 0.25 * t, 6),
            "liquid_share_central": round(0.15 + 0.45 * t, 6),
            "liquid_share_high": round(0.2 + 0.65 * t, 6)
        })
    write_csv("illustrative_quarterly.csv", rows)
    weights = [0, 0, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2]
    write_csv("illustrative_retirement.csv", [
        {"age_quarter": age, "probability": value / sum(weights)}
        for age, value in enumerate(weights, 1)
    ])
    grids = []
    for name, end in (("steady", 1.0), ("transition", 0.5)):
        for q in range(24):
            grids.append({"background": name, "period": f"Q{q + 1:02}",
                          "CC": 1 + (end - 1) * q / 23,
                          "HTC": 1 + (end - 1) * 0.6 * q / 23,
                          "CED": 1 + (end - 1) * 0.8 * q / 23})
    write_csv("illustrative_electricity.csv", grids)
    factors = []
    for phase, multiplier in (("single", 1), ("two", 1.5)):
        activities = {"coolant_supply": [2, 2e-8, 20], "coolant_treatment": [0.5, 1e-8, 5],
                      "coolant_recovery": [0.2, 0.5e-8, 3], "cooling_electricity": [0.4, 1e-8, 8]}
        for activity, values in activities.items():
            for indicator, value, unit in zip(("CC", "HTC", "CED"), values, ("kg CO2-eq", "CTUh", "MJ-eq")):
                factors.append({"phase": phase, "activity": activity, "indicator": indicator,
                                "factor": value * (1 if activity == "cooling_electricity" else multiplier),
                                "activity_unit": "kWh" if activity == "cooling_electricity" else "kg",
                                "impact_unit": unit})
    write_csv("illustrative_impact_factors.csv", factors)
    print(f"Synthetic inputs written to {ROOT}")


if __name__ == "__main__":
    main()
